### ISSUE TITLE
cleaver ITK dependency

### ISSUE THREAD

**Issue by fbordignon** [lassoan/SlicerSegmentMesher#8]
When building SlicerSegmentMesher with SlicerCAT, the ALL_BUILD target tries to build cleaver as one of the first targets and fail, but if I build it manually after everything else is completed, the build is successful.

I figure it is because there is no depends set to cleaver. Should we include ITK dependency?

Also take a look at this handy package https://pypi.org/project/itk-cleaver/
May be of interest in the future.

I am having the same issues with SlicerJupyter and package pybind11, which btw we have prebuilt wheels on pypi https://pypi.org/project/pybind11/#files

**Comment by lassoan** [comment]
Probably you need to list some targets as dependencies for cleaver, to prevent it from building too early. For example, you can try adding ITK to `set(${proj}_DEPENDS "")` in `c:\D\SlicerSegmentMesher\SuperBuild\External_cleaver.cmake`.

**Comment by fbordignon** [comment]
Ok, thanks! Should we make this change official? I can open a PR for this if it is the case

**Comment by lassoan** [comment]
It should not be a problem to add this change to the extension. We should just add a comment there that it is needed for the case when the module is bundled with Slicer in a custom application (otherwise a future developer may remove it as unnecessary noise, because extensions may be assumed to be built after Slicer build is completed).

**Comment by lassoan** [comment]
What operating system has the error occurred on? Did you enable some parallel build options manually?

**Comment by fbordignon** [comment]
Windows
Enabled CMAKE_CXX_MP_FLAG with 12 cores.
Adding ITK to depends seems to do the trick
`set(${proj}_DEPENDS ITK)`

I am building from scratch again to be sure.

**Comment by lassoan** [comment]
> Enabled CMAKE_CXX_MP_FLAG with 12 cores.

We've tried CMAKE_CXX_MP_FLAG  a few times over the years, but the speed improvement (a few ten percent faster) did not seem to worth the extra complications caused by the random build order of targets. Do you know your build time with and without using CMAKE_CXX_MP_FLAG?

> I am building from scratch again to be sure.

Sounds good. If all works well then submit a pull request with the change.

**Comment by fbordignon** [comment]
> > Enabled CMAKE_CXX_MP_FLAG with 12 cores.
> 
> We've tried CMAKE_CXX_MP_FLAG a few times over the years, but the speed improvement (a few ten percent faster) did not seem to worth the extra complications caused by the random build order of targets. Do you know your build time with and without using CMAKE_CXX_MP_FLAG?

4 hours with parallel compiling and 5 hours without using a 6-core i7-7800x 12 threads on a regular SSD.
